# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']


    app.image_uploader:
        class: AppBundle\Services\FileUploader\FileUploader
        arguments: ['%images_directory%']

    app.doctrine_image_listener:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@app.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }


    app.notification:
        class: AppBundle\Services\Notification\Notification
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine.orm.entity_manager"

    app.send_contact_mail:
        class: AppBundle\Services\ContactMail\ContactMail
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine.orm.entity_manager"