# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']


    app.image_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%images_directory%']

    app.doctrine_image_listener:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@app.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

<<<<<<< HEAD
    app.notification:
        class: AppBundle\Services\Notification
=======
    app.send_contact_mail:
        class: AppBundle\Services\ContactMail\ContactMail
>>>>>>> a32e5888e431439b9040820003fcfd56c2d2503c
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine.orm.entity_manager"
<<<<<<< HEAD

=======
>>>>>>> a32e5888e431439b9040820003fcfd56c2d2503c
