# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.notification:
        class: AppBundle\Services\Notification\Notification
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine.orm.entity_manager"

    app.send_contact_mail:
        class: AppBundle\Services\ContactMail\ContactMail
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine.orm.entity_manager"

    app.antispam:
        class: AppBundle\Services\Antispam\Antispam

    app.export_obs:
        class: AppBundle\Services\ExportObservations\ExportObservation

